apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment-tc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tc
  template:
    metadata:
      labels:
        app: api-tc
    spec:
      containers:
      - name: api-container-tc
        image: __ACR_LOGIN_SERVER__/lanchonete-api:__IMAGE_TAG__
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-configmap-tc