apiVersion: v1
kind: Service
metadata:
  name: api-service-tc
  # Cria um IP privado dentro da subnet do AKS, acess√≠vel apenas pela VNet.
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer 
  selector:
    app: api-tc
  ports:
  - protocol: TCP
    port: 80           
    targetPort: 8080  