apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-categories-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"

  MongoDb__DatabaseName: "CategoriesDB"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-categories-deployment
  labels:
    app: ms-categories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-categories
  template:
    metadata:
      labels:
        app: ms-categories
    spec:
      containers:
        - name: ms-categories-container
          image: __ACR_LOGIN_SERVER__/__IMAGE_NAME__:__IMAGE_TAG__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /categories/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /categories/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          envFrom:
            - secretRef:
                name: ms-categories-secrets
            - configMapRef:
                name: ms-categories-configmap
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-categories-service
  labels:
    app: ms-categories
spec:
  type: ClusterIP
  selector:
    app: ms-categories
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-categories-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-categories-deployment
  minReplicas: 1
  maxReplicas: 9
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
